version: "3.9"

name: "bun-hono-template"

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=bunhonotemplate
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0.8-rc0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker/mongodb:/data/db

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.9.1
    container_name: openobserve
    restart: always
    ports:
      - 5080:5080
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=root@bunhonotemplate.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123
    volumes:
      - ./docker/openobserve/data:/data/db

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    container_name: otel-collector
    restart: always
    depends_on:
      - openobserve
    ports:
      - 1888:1888 # pprof extension
      - 55679:55679 # zpages extension
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    volumes:
      - ./configuration/otel/config.yaml:/etc/otelcol-contrib/config.yaml

networks:
  default:
    name: bunhonotemplate-com
